version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "dev"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "dev"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"